Building/urls.py
from django.conf.urls import url
from . import views

app_name = 'Building'

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<building_id>[^/]+)/buy/$', views.buy, name='buy'),
]

MafGame/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('Player.urls')),
    url(r'^building/', include('Building.urls')),
    url(r'^unit/', include('Unit.urls')),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
]

Unit/urls.py
from django.conf.urls import url
from . import views

app_name = 'Unit'

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<unit_id>[^/]+)/buy/$', views.buy, name='buy'),
    url(r'^players/$', views.players, name='players'),
    url(r'^players/attack/$', views.attack, name='attack')
]

Building/models.py
from django.db import models
from Player.models import player


# Create your models here.
class building(models.Model):
    building_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    perminute = models.BigIntegerField()
    cost = models.BigIntegerField()
    multiplier = models.FloatField()
    requiredxp = models.BigIntegerField()

    def upgrade(self, player):
        pb = player_building.objects.get(player_id=player, building_id=self)
        if player.money >= pb.cost:
            player.money -= pb.cost
            pb.level += 1
            pb.cost *= self.multiplier
            pb.perminute += self.perminute
            player.save()
            pb.save()
        else:
            return False

    def __str__(self):
        return self.name


class player_building(models.Model):
    id = models.AutoField(primary_key=True)
    player_id = models.ForeignKey(player)
    building_id = models.ForeignKey(building)
    level = models.IntegerField()
    perminute = models.BigIntegerField()
    cost = models.BigIntegerField()

    def __str__(self):
        return str(self.player_id.user) + " - " + str(self.building_id.name)

def generate_money():
    players = player.objects.all()
    for p in players:
        pb = player_building.objects.filter(player_id=p)
        for building in pb:
            p.money += building.perminute
        p.save()

Building/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

# Create your views here.
from Player.models import player
from .models import building, player_building

global result
result = ""

def post_list(request):
    u = User.objects.get(username=request.user)
    p = player.objects.get(user=u)
    pbs = player_building.objects.filter(player_id=p).all()
    result2 = result
    global result
    result = ""
    return render(request, 'building/post_list.html', {'pbs': pbs, 'result': result2})


def buy(request, building_id):
    global result
    p = player.objects.get(user=User.objects.get(username=request.user))
    b = building.objects.get(name=building_id)
    pb = player_building.objects.get(building_id=b, player_id=p)
    if pb.building_id.upgrade(p) != False:
        result += "Transaction successfull"
    else:
        result += "Not enough money"
    return redirect('/building')

Building/templates/building/post_list.html
{% extends 'base.html' %}

{% block content %}
    {% if result %}
        <p>{{ result }}</p>
    {% endif %}
    <ul class="list-inline">
        {% for pb in pbs %}
            <li>
                <div>
                    <form action="{% url 'Building:buy' pb.building_id %}" method="post">
                        {% csrf_token %}
                        <p>{{ pb.building_id }}</p>
                        <p>Level: {{ pb.level }}</p>
                        <p>Per minute: {{ pb.perminute }}</p>
                        <p>Cost: {{ pb.cost }}</p>
                        <input type="hidden" value="{{ pb.building_id }}" name="building_id">
                        <input type="submit" value="Buy">
                    </form>
                </div>
            </li>
        {% endfor %}
        </ul>




{% endblock %}